### ISSUE TITLE
vue3.1.2 webpack打包出错的问题

### ISSUE THREAD

**Issue by liwanchao4** [vuejs/vuex#1656]
.gitlab-ci.yml

```
.package:
  stage: package
  before_script:
    - npm config set registry http://nexus.sjgs/repository/npm-group/
  artifacts:
    paths:
      - dist
# 测试环境
package-staging:
    extends: .package
    script:      
      - npm install
      - npm run build-staging --verbose
    only:
    - pre_production
```

build的时候报错如下：
![image](https://user-images.githubusercontent.com/43988736/70681714-4175b180-1cd7-11ea-9733-ec49b6133403.png)

将vuex降级到3.1.1版本就没有问题
